# Generated by Django 5.2.4 on 2025-07-15 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_product_quantity_alter_product_sale_percentage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='rates',
            new_name='rate',
        ),
    ]
