# Generated by Django 5.2.4 on 2025-07-17 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_rename_rates_review_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
