# Generated by Django 5.2.4 on 2025-07-24 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0009_alter_cartitem_product_alter_order_payment_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total_amount',
            new_name='total_items',
        ),
    ]
