# Generated by Django 5.2.4 on 2025-07-24 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0010_rename_total_amount_order_total_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_items',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
