# Generated by Django 5.2.4 on 2025-07-25 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0011_alter_order_total_items_alter_order_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'جارٍ التوصيل'), ('DELEVERD', 'تم التوصيل'), ('FAILED', 'فشل التوصيل'), ('RETRIEVED', 'تم الاسترجاع')], default='PENDING', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'جاري'), ('PAID', 'تم الدفع'), ('FAILED', 'فشل'), ('REFUNDED', 'تم استرداد المبلغ')], default='PENDING', max_length=50),
        ),
    ]
