# Generated by Django 5.2.4 on 2025-07-25 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0012_order_status_alter_order_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='num_of_sales',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'قيد الانتظار'), ('PAID', 'تم الدفع'), ('FAILED', 'فشل'), ('REFUNDED', 'تم استرداد المبلغ')], default='PENDING', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'قيد التوصيل'), ('DELEVERD', 'تم التوصيل'), ('FAILED', 'فشل التوصيل'), ('RETRIEVED', 'تم الاسترجاع')], default='PENDING', max_length=50),
        ),
    ]
