# Generated by Django 5.2.4 on 2025-07-26 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0013_product_num_of_sales_alter_order_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'قيد التوصيل'), ('DELIVERED', 'تم التوصيل'), ('FAILED', 'فشل التوصيل'), ('RETRIEVED', 'تم الاسترجاع')], default='PENDING', max_length=50),
        ),
    ]
