# Generated by Django 5.2.4 on 2025-08-05 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0015_order_shipping_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_delivery',
            field=models.BooleanField(default=False),
        ),
    ]
