# Generated by Django 5.2.4 on 2025-08-27 23:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0019_order_total_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellersApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('description', models.TextField()),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('request_status', models.CharField(choices=[('PENDING', 'جاري المراجعة'), ('REJECTED', 'مرفوض'), ('APPROVED', 'مقبول')], default='PENDING', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SellerDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='seller_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='API.sellersapplication')),
            ],
        ),
    ]
