# Generated by Django 5.2.4 on 2025-08-27 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0020_sellersapplication_sellerdocuments'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellersapplication',
            name='business_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
