# Generated by Django 5.2.4 on 2025-09-04 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0021_sellersapplication_business_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellersapplication',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
