# Generated by Django 5.2.4 on 2025-09-08 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0023_coupon_occasion'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='limit',
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AddField(
            model_name='coupon',
            name='limit_per_user',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='coupon',
            name='times_used',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='coupon_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
