# Generated by Django 5.2.4 on 2025-09-16 21:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0026_alter_order_user_alter_review_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'قيد التوصيل'), ('ON_DELIVERY', 'جاري التوصيل'), ('DELIVERED', 'تم التوصيل'), ('FAILED', 'فشل التوصيل'), ('RETRIEVED', 'تم الاسترجاع')], default='PENDING', max_length=50),
        ),
        migrations.CreateModel(
            name='DeliveryApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('zone', models.CharField(blank=True, max_length=200, null=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('description', models.TextField()),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('request_status', models.CharField(choices=[('PENDING', 'جاري المراجعة'), ('REJECTED', 'مرفوض'), ('APPROVED', 'مقبول')], default='PENDING', max_length=50)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_applications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='Delivery_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='API.deliveryapplication')),
            ],
        ),
    ]
